require("base")
require("theme-tokyonight")
require("ide-treesitter")
require("surround")
require("navigation.telescope")
require("navigation.tree")
require("navigation.which-key")
require("theme.misc")
