#! /bin/sh

sxhkd &

compton --config $HOME/.config/compton/config --paint-on-overlay -b 
redshift -l 53.45:9.5 &

bspc monitor -d web terminal code music V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config initial_polarity 	 second_child
bspc config click_to_focus true

bspc desktop ^1 -l monocle


$HOME/.config/polybar/launch.sh
